attaavv_ui: attaavv_ui.o attaavv.o
	gcc -o attaavv_ui attaavv_ui.o attaavv.o

attaavv_ui.o: ./src/attaavv_ui.c ./src/attaavv.h
	gcc -Wall -W -ansi -pedantic -c ./src/attaavv_ui.c

attaavv.o: ./src/attaavv.c ./src/attaavv.h
	gcc -Wall -W -ansi -pedantic -c ./src/attaavv.c        
